packages:
  - .
  - cli
  - docs

ignoreDepScripts: true

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - '@resvg/resvg-js'
  - better-sqlite3
  - sharp@0.34.5
  - simple-git-hooks@2.13.1

overrides:
  sharp: 0.34.5
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-g52709db6.20260226-1136
  vitest: npm:@voidzero-dev/vite-plus-test@0.0.0-g52709db6.20260226-1136
  storybook: ^10.2.7

packageExtensions:
  '@nuxt/scripts':
    dependencies:
      estree-walker: ^3.0.3

patchedDependencies:
  '@jsr/deno__doc@0.189.1': patches/@jsr__deno__doc@0.189.1.patch

savePrefix: ''

shellEmulator: true
